spring.application.name=exception
spring.web.error.whitelabel.enabled=false

# 스프링 부트 4.x.x 버전에서는 spring.error가 아니라 spring.web.error를 사용한다.

spring.web.error.include-exception=true
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
spring.web.error.include-binding-errors=always


